import { Meta, StoryObj } from '@storybook/react';
import { default as AppBar } from './AppBar';
declare const meta: Meta<typeof AppBar>;
export default meta;
type Story = StoryObj<typeof AppBar>;
export declare const Default: Story;
export declare const WithSignOutButton: Story;
export declare const WithNoBrand: Story;
export declare const ClickableBrand: Story;
export declare const UsageExample: Story;
