import { Meta, StoryObj } from '@storybook/react';
import { BasicMap, BasicMapProps } from './BasicMap';
export declare const allArgs: BasicMapProps;
declare const meta: Meta<typeof BasicMap>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Empty: Story;
export declare const WithMarkers: Story;
export declare const WithPolygons: Story;
export declare const WithPolygonsAndMarkers: Story;
export declare const SelectedMarker: Story;
