import { default as React } from '../../../../../node_modules/react';
import { Meta, StoryObj } from '@storybook/react';
import { ButtonZoomIn } from './ButtonZoomIn';
import { ButtonZoomOut } from './ButtonZoomOut';
declare const meta: Meta;
export default meta;
type ZoomInStory = StoryObj<React.ComponentProps<typeof ButtonZoomIn>>;
export declare const ZoomIn: ZoomInStory;
type ZoomOutStory = StoryObj<React.ComponentProps<typeof ButtonZoomOut>>;
export declare const ZoomOut: ZoomOutStory;
type ToggleStory = StoryObj<{}>;
export declare const ToggleMap: ToggleStory;
