import { Meta, StoryObj } from '@storybook/react';
import { default as Switch } from './Switch';
declare const meta: Meta<typeof Switch>;
export default meta;
type Story = StoryObj<typeof Switch>;
export declare const Default: Story;
export declare const Disabled: Story;
export declare const WithLabel: Story;
export declare const Required: Story;
export declare const NoLabel: Story;
export declare const ExampleWithOnChange: Story;
