import { StoryObj } from '@storybook/react';
import { default as DatePicker } from './DatePicker';
import { default as dayjs } from 'dayjs';
declare const meta: {
    title: string;
    component: import('../../../../../node_modules/react').FC<import('./DatePicker').DatePickerProps>;
    tags: string[];
    parameters: {
        docs: {
            description: {
                component: string;
            };
        };
    };
    decorators: ((Story: import('@storybook/csf').PartialStoryFn<import('@storybook/react').ReactRenderer, {
        desktopModeMediaQuery?: string | undefined;
        slots?: import('@mui/x-date-pickers/DatePicker').DatePickerSlots | undefined;
        slotProps?: import('@mui/x-date-pickers/DatePicker').DatePickerSlotProps<true> | undefined;
        yearsPerRow?: (3 | 4) | undefined;
        closeOnSelect?: boolean | undefined;
        viewRenderers?: Partial<import('@mui/x-date-pickers/DatePicker/shared').DatePickerViewRenderers<import('@mui/x-date-pickers/models').DateView>> | undefined;
        defaultValue?: import('@mui/x-date-pickers/internals').PickerValue | undefined;
        autoFocus?: boolean | undefined;
        className?: string | undefined;
        onChange?: ((value: import('@mui/x-date-pickers/internals').PickerValue, context: import('@mui/x-date-pickers/models').PickerChangeHandlerContext<import('@mui/x-date-pickers/models').DateValidationError>) => void) | undefined;
        onError?: ((error: import('@mui/x-date-pickers/models').DateValidationError, value: import('@mui/x-date-pickers/internals').PickerValue) => void) | undefined;
        view?: import('@mui/x-date-pickers/models').DateView | undefined;
        orientation?: import('@mui/x-date-pickers/internals/models').PickerOrientation | undefined;
        sx?: import('@mui/material').SxProps<import('@mui/material').Theme> | undefined;
        disabled?: boolean | undefined;
        value: dayjs.Dayjs | null;
        readOnly?: boolean | undefined;
        openTo?: import('@mui/x-date-pickers/models').DateView | undefined;
        views?: readonly import('@mui/x-date-pickers/models').DateView[] | undefined;
        onViewChange?: ((view: import('@mui/x-date-pickers/models').DateView) => void) | undefined;
        localeText?: import('@mui/x-date-pickers/locales').PickersInputComponentLocaleText | undefined;
        onAccept?: ((value: import('@mui/x-date-pickers/internals').PickerValue, context: import('@mui/x-date-pickers/models').PickerChangeHandlerContext<import('@mui/x-date-pickers/models').DateValidationError>) => void) | undefined;
        referenceDate?: dayjs.Dayjs | undefined;
        reduceAnimations?: boolean | undefined;
        timezone?: import('@mui/x-date-pickers/models').PickersTimezone | undefined;
        renderLoading?: (() => import('../../../../../node_modules/react').ReactNode) | undefined;
        onYearChange?: ((year: import('@mui/x-date-pickers/models').PickerValidDate) => void) | undefined;
        onMonthChange?: ((month: import('@mui/x-date-pickers/models').PickerValidDate) => void) | undefined;
        loading?: boolean | undefined;
        dayOfWeekFormatter?: ((date: import('@mui/x-date-pickers/models').PickerValidDate) => string) | undefined;
        displayWeekNumber?: boolean | undefined;
        fixedWeekNumber?: number | undefined;
        disableHighlightToday?: boolean | undefined;
        showDaysOutsideCurrentMonth?: boolean | undefined;
        monthsPerRow?: (3 | 4) | undefined;
        yearsOrder?: ("asc" | "desc") | undefined;
        shouldDisableDate?: ((day: import('@mui/x-date-pickers/models').PickerValidDate) => boolean) | undefined;
        shouldDisableMonth?: ((month: import('@mui/x-date-pickers/models').PickerValidDate) => boolean) | undefined;
        shouldDisableYear?: ((year: import('@mui/x-date-pickers/models').PickerValidDate) => boolean) | undefined;
        maxDate?: import('@mui/x-date-pickers/models').PickerValidDate | undefined;
        minDate?: import('@mui/x-date-pickers/models').PickerValidDate | undefined;
        disablePast?: boolean | undefined;
        disableFuture?: boolean | undefined;
        open?: boolean | undefined;
        onClose?: (() => void) | undefined;
        onOpen?: (() => void) | undefined;
        format?: string | undefined;
        disableOpenPicker?: boolean | undefined;
        label?: string | (import('../../../../../node_modules/react').ReactElement<any, string | import('../../../../../node_modules/react').JSXElementConstructor<any>> & string) | (Iterable<import('../../../../../node_modules/react').ReactNode> & string) | (import('../../../../../node_modules/react').ReactPortal & string) | undefined;
        inputRef?: React.Ref<HTMLInputElement> | undefined;
        name?: string | undefined;
        formatDensity?: ("dense" | "spacious") | undefined;
        enableAccessibleFieldDOMStructure?: any;
        selectedSections?: import('@mui/x-date-pickers/models').FieldSelectedSections | undefined;
        onSelectedSectionsChange?: ((newValue: import('@mui/x-date-pickers/models').FieldSelectedSections) => void) | undefined;
        error?: boolean | undefined;
        helperText?: string | undefined;
        textFieldProps?: import('@mui/material').TextFieldProps | undefined;
        errorMsg?: String | undefined;
        fullWidth?: boolean | undefined;
    }>) => import("@emotion/react/jsx-runtime").JSX.Element)[];
};
export default meta;
type Story = StoryObj<typeof DatePicker>;
export declare const Default: Story;
export declare const ErrorState: Story;
export declare const WithDateRestrictions: Story;
