import { Meta, StoryObj } from '@storybook/react';
import { default as Brand } from './Brand';
declare const meta: Meta<typeof Brand>;
export default meta;
type Story = StoryObj<typeof Brand>;
export declare const Default: Story;
export declare const WithBeta: Story;
export declare const Jumbo: Story;
export declare const WithoutAppName: Story;
export declare const AsLink: Story;
export declare const OnDarkBackground: Story;
