import type { ComponentProps } from "react";
import MuiAlertTitle from "@mui/material/AlertTitle";

// DRAFT scaffold generated by mui-audit — ds had no equivalent for MUI's
// AlertTitle, which is used directly in 1 file(s) in the scanned repo.
// Props seen in real usage: none observed.
// Replace this passthrough with the proper ds-themed implementation, then wire it
// into the category barrel + src/export.ts before release.
export type AlertTitleProps = ComponentProps<typeof MuiAlertTitle>;

export const AlertTitle = (props: AlertTitleProps) => <MuiAlertTitle {...props} />;
