import { StoryObj } from '@storybook/react';
import { default as DateTimePicker } from './DateTimePicker';
import { default as dayjs } from 'dayjs';
declare const meta: {
    title: string;
    component: import('../../../../../node_modules/react').FC<import('./DateTimePicker').DateTimePickerProps>;
    tags: string[];
    parameters: {
        docs: {
            description: {
                component: string;
            };
        };
    };
    decorators: ((Story: import('@storybook/csf').PartialStoryFn<import('@storybook/react').ReactRenderer, {
        desktopModeMediaQuery?: string | undefined;
        slots?: import('@mui/x-date-pickers/DateTimePicker').DateTimePickerSlots | undefined;
        slotProps?: import('@mui/x-date-pickers/DateTimePicker').DateTimePickerSlotProps<true> | undefined;
        yearsPerRow?: (3 | 4) | undefined;
        views?: readonly import('@mui/x-date-pickers/models').DateOrTimeView[] | undefined;
        ampmInClock?: boolean | undefined;
        viewRenderers?: Partial<import('@mui/x-date-pickers/DateTimePicker/shared').DateTimePickerViewRenderers<import('@mui/x-date-pickers/internals').DateOrTimeViewWithMeridiem>> | undefined;
        defaultValue?: import('@mui/x-date-pickers/internals').PickerValue | undefined;
        autoFocus?: boolean | undefined;
        className?: string | undefined;
        onChange?: ((value: import('@mui/x-date-pickers/internals').PickerValue, context: import('@mui/x-date-pickers/models').PickerChangeHandlerContext<import('@mui/x-date-pickers/models').DateTimeValidationError>) => void) | undefined;
        onError?: ((error: import('@mui/x-date-pickers/models').DateTimeValidationError, value: import('@mui/x-date-pickers/internals').PickerValue) => void) | undefined;
        view?: import('@mui/x-date-pickers/internals').DateOrTimeViewWithMeridiem | undefined;
        orientation?: import('@mui/x-date-pickers/internals/models').PickerOrientation | undefined;
        sx?: import('@mui/material').SxProps<import('@mui/material').Theme> | undefined;
        disabled?: boolean | undefined;
        value?: import('@mui/x-date-pickers/internals').PickerValue | undefined;
        readOnly?: boolean | undefined;
        openTo?: import('@mui/x-date-pickers/internals').DateOrTimeViewWithMeridiem | undefined;
        onViewChange?: ((view: import('@mui/x-date-pickers/internals').DateOrTimeViewWithMeridiem) => void) | undefined;
        localeText?: import('@mui/x-date-pickers/locales').PickersInputComponentLocaleText | undefined;
        onAccept?: ((value: import('@mui/x-date-pickers/internals').PickerValue, context: import('@mui/x-date-pickers/models').PickerChangeHandlerContext<import('@mui/x-date-pickers/models').DateTimeValidationError>) => void) | undefined;
        referenceDate?: dayjs.Dayjs | undefined;
        reduceAnimations?: boolean | undefined;
        timezone?: import('@mui/x-date-pickers/models').PickersTimezone | undefined;
        loading?: boolean | undefined;
        disableFuture?: boolean | undefined;
        disablePast?: boolean | undefined;
        shouldDisableDate?: ((day: import('@mui/x-date-pickers/models').PickerValidDate) => boolean) | undefined;
        shouldDisableMonth?: ((month: import('@mui/x-date-pickers/models').PickerValidDate) => boolean) | undefined;
        shouldDisableYear?: ((year: import('@mui/x-date-pickers/models').PickerValidDate) => boolean) | undefined;
        minDate?: import('@mui/x-date-pickers/models').PickerValidDate | undefined;
        maxDate?: import('@mui/x-date-pickers/models').PickerValidDate | undefined;
        renderLoading?: (() => import('../../../../../node_modules/react').ReactNode) | undefined;
        onYearChange?: ((year: import('@mui/x-date-pickers/models').PickerValidDate) => void) | undefined;
        onMonthChange?: ((month: import('@mui/x-date-pickers/models').PickerValidDate) => void) | undefined;
        dayOfWeekFormatter?: ((date: import('@mui/x-date-pickers/models').PickerValidDate) => string) | undefined;
        displayWeekNumber?: boolean | undefined;
        fixedWeekNumber?: number | undefined;
        disableHighlightToday?: boolean | undefined;
        showDaysOutsideCurrentMonth?: boolean | undefined;
        monthsPerRow?: (3 | 4) | undefined;
        yearsOrder?: ("asc" | "desc") | undefined;
        thresholdToRenderTimeInASingleColumn?: number | undefined;
        timeSteps?: import('@mui/x-date-pickers/models').TimeStepOptions | undefined;
        minutesStep?: number | undefined;
        minTime?: import('@mui/x-date-pickers/models').PickerValidDate | undefined;
        maxTime?: import('@mui/x-date-pickers/models').PickerValidDate | undefined;
        shouldDisableTime?: ((value: import('@mui/x-date-pickers/models').PickerValidDate, view: import('@mui/x-date-pickers/models').TimeView) => boolean) | undefined;
        disableIgnoringDatePartForTimeValidation?: boolean | undefined;
        ampm?: boolean | undefined;
        skipDisabled?: boolean | undefined;
        minDateTime?: import('@mui/x-date-pickers/models').PickerValidDate | undefined;
        maxDateTime?: import('@mui/x-date-pickers/models').PickerValidDate | undefined;
        closeOnSelect?: boolean | undefined;
        open?: boolean | undefined;
        onClose?: (() => void) | undefined;
        onOpen?: (() => void) | undefined;
        format?: string | undefined;
        disableOpenPicker?: boolean | undefined;
        label?: React.ReactNode;
        inputRef?: React.Ref<HTMLInputElement> | undefined;
        name?: string | undefined;
        formatDensity?: ("dense" | "spacious") | undefined;
        enableAccessibleFieldDOMStructure?: any;
        selectedSections?: import('@mui/x-date-pickers/models').FieldSelectedSections | undefined;
        onSelectedSectionsChange?: ((newValue: import('@mui/x-date-pickers/models').FieldSelectedSections) => void) | undefined;
        textFieldProps?: import('@mui/material').TextFieldProps | undefined;
        helperText?: string | undefined;
        fullWidth?: boolean | undefined;
        errorMsg?: string | undefined;
        error?: boolean | undefined;
    }>) => import("@emotion/react/jsx-runtime").JSX.Element)[];
};
export default meta;
type Story = StoryObj<typeof DateTimePicker>;
export declare const Default: Story;
export declare const ErrorState: Story;
export declare const WithDateRestrictions: Story;
