import { Meta, StoryObj } from '@storybook/react';
import { Menu } from './Menu';
declare const meta: Meta<typeof Menu>;
export default meta;
type Story = StoryObj<typeof Menu>;
export declare const Default: Story;
export declare const WithIconsAndDisabled: Story;
export declare const LinkNavigation: Story;
export declare const WithDividerAndOnSelect: Story;
export declare const WithSelected: Story;
