import { Meta, StoryObj } from '@storybook/react';
import { default as Autocomplete } from './Autocomplete';
declare const meta: Meta<typeof Autocomplete>;
export default meta;
type Story = StoryObj<typeof Autocomplete>;
export declare const Basic: Story;
export declare const Preselected: Story;
export declare const WithHelperText: Story;
export declare const Disabled: Story;
export declare const AsyncLoading: Story;
export declare const StoresIdInFormState: Story;
export declare const MultiSelectWithLimit: Story;
