import { Meta, StoryObj } from '@storybook/react';
import { default as Spinner } from './Spinner';
declare const meta: Meta<typeof Spinner>;
export default meta;
type Story = StoryObj<typeof Spinner>;
export declare const Default: Story;
export declare const Small: Story;
export declare const Large: Story;
export declare const Determinate: Story;
export declare const InContainer: Story;
